
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Tabla_simbolos {
  /* terminals */
  public static final int r_negro = 23;
  public static final int r_azul = 16;
  public static final int r_cuadrado = 4;
  public static final int s_resta = 12;
  public static final int r_linea = 6;
  public static final int r_naranja = 20;
  public static final int r_graficar = 2;
  public static final int r_amarillo = 19;
  public static final int numero = 9;
  public static final int r_rectangulo = 5;
  public static final int s_division = 14;
  public static final int s_parentesisc = 24;
  public static final int r_circulo = 3;
  public static final int s_parentesisa = 8;
  public static final int r_poligono = 7;
  public static final int r_verde = 18;
  public static final int EOF = 0;
  public static final int r_cafe = 22;
  public static final int s_suma = 11;
  public static final int s_multiplicacion = 13;
  public static final int r_rojo = 17;
  public static final int error = 1;
  public static final int numero_entero = 10;
  public static final int s_coma = 15;
  public static final int r_morado = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "r_graficar",
  "r_circulo",
  "r_cuadrado",
  "r_rectangulo",
  "r_linea",
  "r_poligono",
  "s_parentesisa",
  "numero",
  "numero_entero",
  "s_suma",
  "s_resta",
  "s_multiplicacion",
  "s_division",
  "s_coma",
  "r_azul",
  "r_rojo",
  "r_verde",
  "r_amarillo",
  "r_naranja",
  "r_morado",
  "r_cafe",
  "r_negro",
  "s_parentesisc"
  };
}

